spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

mybatis:
  type-aliases-package: org.example.entities
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  devtools:
    restart:
      enabled: true
      additional-paths: src/main

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: microservicecloud-dept8001

info:
  app.name: microservicecloud-hsh-80
  company.name: www.hsh.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001

mybatis:
  type-aliases-package: org.example.entities
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true

spring:
  profiles: test
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  devtools:
    restart:
      enabled: true
      additional-paths: src/main

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: microservicecloud-dept8001

info:
  app.name: microservicecloud-hsh-80
  company.name: www.hsh.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
